SET FOREIGN_KEY_CHECKS=0;
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (102, 'Maria Rodriguez Quispe', '40000001', 'EST-041', 'estEST-041@mail.com', 'Jr. Los Olivos 1', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (103, 'Jose Martinez Condori', '40000002', 'EST-042', 'estEST-042@mail.com', 'Jr. Los Olivos 2', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (104, 'Ana Lopez Mamani', '40000003', 'EST-043', 'estEST-043@mail.com', 'Jr. Los Olivos 3', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (105, 'Luis Gonzalez Huayta', '40000004', 'EST-044', 'estEST-044@mail.com', 'Jr. Los Olivos 4', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (106, 'Rosa Perez Ccama', '40000005', 'EST-045', 'estEST-045@mail.com', 'Jr. Los Olivos 5', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (107, 'Juan Sanchez Chambi', '40000006', 'EST-046', 'estEST-046@mail.com', 'Jr. Los Olivos 6', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (108, 'Carmen Ramirez Hancco', '40000007', 'EST-047', 'estEST-047@mail.com', 'Jr. Los Olivos 7', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (109, 'Pedro Torres Lipa', '40000008', 'EST-048', 'estEST-048@mail.com', 'Jr. Los Olivos 8', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (110, 'Elena Flores Turpo', '40000009', 'EST-049', 'estEST-049@mail.com', 'Jr. Los Olivos 9', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (111, 'Diego Rivera Coila', '40000010', 'EST-050', 'estEST-050@mail.com', 'Jr. Los Olivos 10', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (112, 'Sofia Castillo Yana', '40000011', 'EST-051', 'estEST-051@mail.com', 'Jr. Los Olivos 11', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (113, 'Miguel Reyes Apaza', '40000012', 'EST-052', 'estEST-052@mail.com', 'Jr. Los Olivos 12', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (114, 'Andrea Ortiz Sucasaire', '40000013', 'EST-053', 'estEST-053@mail.com', 'Jr. Los Olivos 13', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (115, 'Pablo Morales Huanca', '40000014', 'EST-054', 'estEST-054@mail.com', 'Jr. Los Olivos 14', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (116, 'Valeria Delgado Umiña', '40000015', 'EST-055', 'estEST-055@mail.com', 'Jr. Los Olivos 15', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (117, 'Fernando Cruz Chura', '40000016', 'EST-056', 'estEST-056@mail.com', 'Jr. Los Olivos 16', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (118, 'Camila Ramos Ticona', '40000017', 'EST-057', 'estEST-057@mail.com', 'Jr. Los Olivos 17', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (119, 'Sergio Vargas Pari', '40000018', 'EST-058', 'estEST-058@mail.com', 'Jr. Los Olivos 18', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (120, 'Lucia Mendoza Vilca', '40000019', 'EST-059', 'estEST-059@mail.com', 'Jr. Los Olivos 19', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (121, 'Carlos Garcia Huaman', '40000020', 'EST-060', 'estEST-060@mail.com', 'Jr. Los Olivos 20', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (122, 'Maria Rodriguez Quispe', '40000021', 'EST-061', 'estEST-061@mail.com', 'Jr. Los Olivos 21', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (123, 'Jose Martinez Condori', '40000022', 'EST-062', 'estEST-062@mail.com', 'Jr. Los Olivos 22', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (124, 'Ana Lopez Mamani', '40000023', 'EST-063', 'estEST-063@mail.com', 'Jr. Los Olivos 23', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (125, 'Luis Gonzalez Huayta', '40000024', 'EST-064', 'estEST-064@mail.com', 'Jr. Los Olivos 24', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (126, 'Rosa Perez Ccama', '40000025', 'EST-065', 'estEST-065@mail.com', 'Jr. Los Olivos 25', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (127, 'Juan Sanchez Chambi', '40000026', 'EST-066', 'estEST-066@mail.com', 'Jr. Los Olivos 26', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (128, 'Carmen Ramirez Hancco', '40000027', 'EST-067', 'estEST-067@mail.com', 'Jr. Los Olivos 27', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (129, 'Pedro Torres Lipa', '40000028', 'EST-068', 'estEST-068@mail.com', 'Jr. Los Olivos 28', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (130, 'Elena Flores Turpo', '40000029', 'EST-069', 'estEST-069@mail.com', 'Jr. Los Olivos 29', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (131, 'Diego Rivera Coila', '40000030', 'EST-070', 'estEST-070@mail.com', 'Jr. Los Olivos 30', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (132, 'Sofia Castillo Yana', '40000031', 'EST-071', 'estEST-071@mail.com', 'Jr. Los Olivos 31', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (133, 'Miguel Reyes Apaza', '40000032', 'EST-072', 'estEST-072@mail.com', 'Jr. Los Olivos 32', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (134, 'Andrea Ortiz Sucasaire', '40000033', 'EST-073', 'estEST-073@mail.com', 'Jr. Los Olivos 33', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (135, 'Pablo Morales Huanca', '40000034', 'EST-074', 'estEST-074@mail.com', 'Jr. Los Olivos 34', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (136, 'Valeria Delgado Umiña', '40000035', 'EST-075', 'estEST-075@mail.com', 'Jr. Los Olivos 35', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (137, 'Fernando Cruz Chura', '40000036', 'EST-076', 'estEST-076@mail.com', 'Jr. Los Olivos 36', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (138, 'Camila Ramos Ticona', '40000037', 'EST-077', 'estEST-077@mail.com', 'Jr. Los Olivos 37', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (139, 'Sergio Vargas Pari', '40000038', 'EST-078', 'estEST-078@mail.com', 'Jr. Los Olivos 38', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (140, 'Lucia Mendoza Vilca', '40000039', 'EST-079', 'estEST-079@mail.com', 'Jr. Los Olivos 39', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (141, 'Carlos Garcia Huaman', '40000040', 'EST-080', 'estEST-080@mail.com', 'Jr. Los Olivos 40', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (142, 'Maria Rodriguez Quispe', '40000041', 'EST-081', 'estEST-081@mail.com', 'Jr. Los Olivos 41', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (143, 'Jose Martinez Condori', '40000042', 'EST-082', 'estEST-082@mail.com', 'Jr. Los Olivos 42', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (144, 'Ana Lopez Mamani', '40000043', 'EST-083', 'estEST-083@mail.com', 'Jr. Los Olivos 43', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (145, 'Luis Gonzalez Huayta', '40000044', 'EST-084', 'estEST-084@mail.com', 'Jr. Los Olivos 44', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (146, 'Rosa Perez Ccama', '40000045', 'EST-085', 'estEST-085@mail.com', 'Jr. Los Olivos 45', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (147, 'Juan Sanchez Chambi', '40000046', 'EST-086', 'estEST-086@mail.com', 'Jr. Los Olivos 46', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (148, 'Carmen Ramirez Hancco', '40000047', 'EST-087', 'estEST-087@mail.com', 'Jr. Los Olivos 47', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (149, 'Pedro Torres Lipa', '40000048', 'EST-088', 'estEST-088@mail.com', 'Jr. Los Olivos 48', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (150, 'Elena Flores Turpo', '40000049', 'EST-089', 'estEST-089@mail.com', 'Jr. Los Olivos 49', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (151, 'Diego Rivera Coila', '40000050', 'EST-090', 'estEST-090@mail.com', 'Jr. Los Olivos 50', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (152, 'Sofia Castillo Yana', '40000051', 'EST-091', 'estEST-091@mail.com', 'Jr. Los Olivos 51', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (153, 'Miguel Reyes Apaza', '40000052', 'EST-092', 'estEST-092@mail.com', 'Jr. Los Olivos 52', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (154, 'Andrea Ortiz Sucasaire', '40000053', 'EST-093', 'estEST-093@mail.com', 'Jr. Los Olivos 53', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (155, 'Pablo Morales Huanca', '40000054', 'EST-094', 'estEST-094@mail.com', 'Jr. Los Olivos 54', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (156, 'Valeria Delgado Umiña', '40000055', 'EST-095', 'estEST-095@mail.com', 'Jr. Los Olivos 55', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (157, 'Fernando Cruz Chura', '40000056', 'EST-096', 'estEST-096@mail.com', 'Jr. Los Olivos 56', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (158, 'Camila Ramos Ticona', '40000057', 'EST-097', 'estEST-097@mail.com', 'Jr. Los Olivos 57', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (159, 'Sergio Vargas Pari', '40000058', 'EST-098', 'estEST-098@mail.com', 'Jr. Los Olivos 58', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (160, 'Lucia Mendoza Vilca', '40000059', 'EST-099', 'estEST-099@mail.com', 'Jr. Los Olivos 59', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (161, 'Carlos Garcia Huaman', '40000060', 'EST-100', 'estEST-100@mail.com', 'Jr. Los Olivos 60', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (162, 'Maria Rodriguez Quispe', '40000061', 'EST-101', 'estEST-101@mail.com', 'Jr. Los Olivos 61', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (163, 'Jose Martinez Condori', '40000062', 'EST-102', 'estEST-102@mail.com', 'Jr. Los Olivos 62', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (164, 'Ana Lopez Mamani', '40000063', 'EST-103', 'estEST-103@mail.com', 'Jr. Los Olivos 63', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (165, 'Luis Gonzalez Huayta', '40000064', 'EST-104', 'estEST-104@mail.com', 'Jr. Los Olivos 64', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (166, 'Rosa Perez Ccama', '40000065', 'EST-105', 'estEST-105@mail.com', 'Jr. Los Olivos 65', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (167, 'Juan Sanchez Chambi', '40000066', 'EST-106', 'estEST-106@mail.com', 'Jr. Los Olivos 66', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (168, 'Carmen Ramirez Hancco', '40000067', 'EST-107', 'estEST-107@mail.com', 'Jr. Los Olivos 67', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (169, 'Pedro Torres Lipa', '40000068', 'EST-108', 'estEST-108@mail.com', 'Jr. Los Olivos 68', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (170, 'Elena Flores Turpo', '40000069', 'EST-109', 'estEST-109@mail.com', 'Jr. Los Olivos 69', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (171, 'Diego Rivera Coila', '40000070', 'EST-110', 'estEST-110@mail.com', 'Jr. Los Olivos 70', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (172, 'Sofia Castillo Yana', '40000071', 'EST-111', 'estEST-111@mail.com', 'Jr. Los Olivos 71', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (173, 'Miguel Reyes Apaza', '40000072', 'EST-112', 'estEST-112@mail.com', 'Jr. Los Olivos 72', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (174, 'Andrea Ortiz Sucasaire', '40000073', 'EST-113', 'estEST-113@mail.com', 'Jr. Los Olivos 73', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (175, 'Pablo Morales Huanca', '40000074', 'EST-114', 'estEST-114@mail.com', 'Jr. Los Olivos 74', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (176, 'Valeria Delgado Umiña', '40000075', 'EST-115', 'estEST-115@mail.com', 'Jr. Los Olivos 75', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (177, 'Fernando Cruz Chura', '40000076', 'EST-116', 'estEST-116@mail.com', 'Jr. Los Olivos 76', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (178, 'Camila Ramos Ticona', '40000077', 'EST-117', 'estEST-117@mail.com', 'Jr. Los Olivos 77', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (179, 'Sergio Vargas Pari', '40000078', 'EST-118', 'estEST-118@mail.com', 'Jr. Los Olivos 78', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (180, 'Lucia Mendoza Vilca', '40000079', 'EST-119', 'estEST-119@mail.com', 'Jr. Los Olivos 79', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (181, 'Carlos Garcia Huaman', '40000080', 'EST-120', 'estEST-120@mail.com', 'Jr. Los Olivos 80', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (182, 'Maria Rodriguez Quispe', '40000081', 'EST-121', 'estEST-121@mail.com', 'Jr. Los Olivos 81', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (183, 'Jose Martinez Condori', '40000082', 'EST-122', 'estEST-122@mail.com', 'Jr. Los Olivos 82', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (184, 'Ana Lopez Mamani', '40000083', 'EST-123', 'estEST-123@mail.com', 'Jr. Los Olivos 83', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (185, 'Luis Gonzalez Huayta', '40000084', 'EST-124', 'estEST-124@mail.com', 'Jr. Los Olivos 84', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (186, 'Rosa Perez Ccama', '40000085', 'EST-125', 'estEST-125@mail.com', 'Jr. Los Olivos 85', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (187, 'Juan Sanchez Chambi', '40000086', 'EST-126', 'estEST-126@mail.com', 'Jr. Los Olivos 86', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (188, 'Carmen Ramirez Hancco', '40000087', 'EST-127', 'estEST-127@mail.com', 'Jr. Los Olivos 87', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (189, 'Pedro Torres Lipa', '40000088', 'EST-128', 'estEST-128@mail.com', 'Jr. Los Olivos 88', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (190, 'Elena Flores Turpo', '40000089', 'EST-129', 'estEST-129@mail.com', 'Jr. Los Olivos 89', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (191, 'Diego Rivera Coila', '40000090', 'EST-130', 'estEST-130@mail.com', 'Jr. Los Olivos 90', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (192, 'Sofia Castillo Yana', '40000091', 'EST-131', 'estEST-131@mail.com', 'Jr. Los Olivos 91', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (193, 'Miguel Reyes Apaza', '40000092', 'EST-132', 'estEST-132@mail.com', 'Jr. Los Olivos 92', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (194, 'Andrea Ortiz Sucasaire', '40000093', 'EST-133', 'estEST-133@mail.com', 'Jr. Los Olivos 93', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (195, 'Pablo Morales Huanca', '40000094', 'EST-134', 'estEST-134@mail.com', 'Jr. Los Olivos 94', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (196, 'Valeria Delgado Umiña', '40000095', 'EST-135', 'estEST-135@mail.com', 'Jr. Los Olivos 95', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (197, 'Fernando Cruz Chura', '40000096', 'EST-136', 'estEST-136@mail.com', 'Jr. Los Olivos 96', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (198, 'Camila Ramos Ticona', '40000097', 'EST-137', 'estEST-137@mail.com', 'Jr. Los Olivos 97', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (199, 'Sergio Vargas Pari', '40000098', 'EST-138', 'estEST-138@mail.com', 'Jr. Los Olivos 98', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (200, 'Lucia Mendoza Vilca', '40000099', 'EST-139', 'estEST-139@mail.com', 'Jr. Los Olivos 99', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (201, 'Carlos Garcia Huaman', '40000100', 'EST-140', 'estEST-140@mail.com', 'Jr. Los Olivos 100', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (202, 'Maria Rodriguez Quispe', '40000101', 'EST-141', 'estEST-141@mail.com', 'Jr. Los Olivos 101', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (203, 'Jose Martinez Condori', '40000102', 'EST-142', 'estEST-142@mail.com', 'Jr. Los Olivos 102', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (204, 'Ana Lopez Mamani', '40000103', 'EST-143', 'estEST-143@mail.com', 'Jr. Los Olivos 103', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (205, 'Luis Gonzalez Huayta', '40000104', 'EST-144', 'estEST-144@mail.com', 'Jr. Los Olivos 104', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (206, 'Rosa Perez Ccama', '40000105', 'EST-145', 'estEST-145@mail.com', 'Jr. Los Olivos 105', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (207, 'Juan Sanchez Chambi', '40000106', 'EST-146', 'estEST-146@mail.com', 'Jr. Los Olivos 106', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (208, 'Carmen Ramirez Hancco', '40000107', 'EST-147', 'estEST-147@mail.com', 'Jr. Los Olivos 107', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (209, 'Pedro Torres Lipa', '40000108', 'EST-148', 'estEST-148@mail.com', 'Jr. Los Olivos 108', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (210, 'Elena Flores Turpo', '40000109', 'EST-149', 'estEST-149@mail.com', 'Jr. Los Olivos 109', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (211, 'Diego Rivera Coila', '40000110', 'EST-150', 'estEST-150@mail.com', 'Jr. Los Olivos 110', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (212, 'Sofia Castillo Yana', '40000111', 'EST-151', 'estEST-151@mail.com', 'Jr. Los Olivos 111', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (213, 'Miguel Reyes Apaza', '40000112', 'EST-152', 'estEST-152@mail.com', 'Jr. Los Olivos 112', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (214, 'Andrea Ortiz Sucasaire', '40000113', 'EST-153', 'estEST-153@mail.com', 'Jr. Los Olivos 113', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (215, 'Pablo Morales Huanca', '40000114', 'EST-154', 'estEST-154@mail.com', 'Jr. Los Olivos 114', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (216, 'Valeria Delgado Umiña', '40000115', 'EST-155', 'estEST-155@mail.com', 'Jr. Los Olivos 115', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (217, 'Fernando Cruz Chura', '40000116', 'EST-156', 'estEST-156@mail.com', 'Jr. Los Olivos 116', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (218, 'Camila Ramos Ticona', '40000117', 'EST-157', 'estEST-157@mail.com', 'Jr. Los Olivos 117', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (219, 'Sergio Vargas Pari', '40000118', 'EST-158', 'estEST-158@mail.com', 'Jr. Los Olivos 118', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (220, 'Lucia Mendoza Vilca', '40000119', 'EST-159', 'estEST-159@mail.com', 'Jr. Los Olivos 119', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (221, 'Carlos Garcia Huaman', '40000120', 'EST-160', 'estEST-160@mail.com', 'Jr. Los Olivos 120', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (222, 'Maria Rodriguez Quispe', '40000121', 'EST-161', 'estEST-161@mail.com', 'Jr. Los Olivos 121', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (223, 'Jose Martinez Condori', '40000122', 'EST-162', 'estEST-162@mail.com', 'Jr. Los Olivos 122', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (224, 'Ana Lopez Mamani', '40000123', 'EST-163', 'estEST-163@mail.com', 'Jr. Los Olivos 123', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (225, 'Luis Gonzalez Huayta', '40000124', 'EST-164', 'estEST-164@mail.com', 'Jr. Los Olivos 124', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (226, 'Rosa Perez Ccama', '40000125', 'EST-165', 'estEST-165@mail.com', 'Jr. Los Olivos 125', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (227, 'Juan Sanchez Chambi', '40000126', 'EST-166', 'estEST-166@mail.com', 'Jr. Los Olivos 126', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (228, 'Carmen Ramirez Hancco', '40000127', 'EST-167', 'estEST-167@mail.com', 'Jr. Los Olivos 127', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (229, 'Pedro Torres Lipa', '40000128', 'EST-168', 'estEST-168@mail.com', 'Jr. Los Olivos 128', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (230, 'Elena Flores Turpo', '40000129', 'EST-169', 'estEST-169@mail.com', 'Jr. Los Olivos 129', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (231, 'Diego Rivera Coila', '40000130', 'EST-170', 'estEST-170@mail.com', 'Jr. Los Olivos 130', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (232, 'Sofia Castillo Yana', '40000131', 'EST-171', 'estEST-171@mail.com', 'Jr. Los Olivos 131', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (233, 'Miguel Reyes Apaza', '40000132', 'EST-172', 'estEST-172@mail.com', 'Jr. Los Olivos 132', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (234, 'Andrea Ortiz Sucasaire', '40000133', 'EST-173', 'estEST-173@mail.com', 'Jr. Los Olivos 133', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (235, 'Pablo Morales Huanca', '40000134', 'EST-174', 'estEST-174@mail.com', 'Jr. Los Olivos 134', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (236, 'Valeria Delgado Umiña', '40000135', 'EST-175', 'estEST-175@mail.com', 'Jr. Los Olivos 135', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (237, 'Fernando Cruz Chura', '40000136', 'EST-176', 'estEST-176@mail.com', 'Jr. Los Olivos 136', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (238, 'Camila Ramos Ticona', '40000137', 'EST-177', 'estEST-177@mail.com', 'Jr. Los Olivos 137', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (239, 'Sergio Vargas Pari', '40000138', 'EST-178', 'estEST-178@mail.com', 'Jr. Los Olivos 138', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (240, 'Lucia Mendoza Vilca', '40000139', 'EST-179', 'estEST-179@mail.com', 'Jr. Los Olivos 139', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (241, 'Carlos Garcia Huaman', '40000140', 'EST-180', 'estEST-180@mail.com', 'Jr. Los Olivos 140', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (242, 'Maria Rodriguez Quispe', '40000141', 'EST-181', 'estEST-181@mail.com', 'Jr. Los Olivos 141', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (243, 'Jose Martinez Condori', '40000142', 'EST-182', 'estEST-182@mail.com', 'Jr. Los Olivos 142', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (244, 'Ana Lopez Mamani', '40000143', 'EST-183', 'estEST-183@mail.com', 'Jr. Los Olivos 143', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (245, 'Luis Gonzalez Huayta', '40000144', 'EST-184', 'estEST-184@mail.com', 'Jr. Los Olivos 144', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (246, 'Rosa Perez Ccama', '40000145', 'EST-185', 'estEST-185@mail.com', 'Jr. Los Olivos 145', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (247, 'Juan Sanchez Chambi', '40000146', 'EST-186', 'estEST-186@mail.com', 'Jr. Los Olivos 146', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (248, 'Carmen Ramirez Hancco', '40000147', 'EST-187', 'estEST-187@mail.com', 'Jr. Los Olivos 147', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (249, 'Pedro Torres Lipa', '40000148', 'EST-188', 'estEST-188@mail.com', 'Jr. Los Olivos 148', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (250, 'Elena Flores Turpo', '40000149', 'EST-189', 'estEST-189@mail.com', 'Jr. Los Olivos 149', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (251, 'Diego Rivera Coila', '40000150', 'EST-190', 'estEST-190@mail.com', 'Jr. Los Olivos 150', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (252, 'Sofia Castillo Yana', '40000151', 'EST-191', 'estEST-191@mail.com', 'Jr. Los Olivos 151', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (253, 'Miguel Reyes Apaza', '40000152', 'EST-192', 'estEST-192@mail.com', 'Jr. Los Olivos 152', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (254, 'Andrea Ortiz Sucasaire', '40000153', 'EST-193', 'estEST-193@mail.com', 'Jr. Los Olivos 153', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (255, 'Pablo Morales Huanca', '40000154', 'EST-194', 'estEST-194@mail.com', 'Jr. Los Olivos 154', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (256, 'Valeria Delgado Umiña', '40000155', 'EST-195', 'estEST-195@mail.com', 'Jr. Los Olivos 155', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (257, 'Fernando Cruz Chura', '40000156', 'EST-196', 'estEST-196@mail.com', 'Jr. Los Olivos 156', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (258, 'Camila Ramos Ticona', '40000157', 'EST-197', 'estEST-197@mail.com', 'Jr. Los Olivos 157', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (259, 'Sergio Vargas Pari', '40000158', 'EST-198', 'estEST-198@mail.com', 'Jr. Los Olivos 158', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (260, 'Lucia Mendoza Vilca', '40000159', 'EST-199', 'estEST-199@mail.com', 'Jr. Los Olivos 159', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (261, 'Carlos Garcia Huaman', '40000160', 'EST-200', 'estEST-200@mail.com', 'Jr. Los Olivos 160', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (262, 'Maria Rodriguez Quispe', '40000161', 'EST-201', 'estEST-201@mail.com', 'Jr. Los Olivos 161', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (263, 'Jose Martinez Condori', '40000162', 'EST-202', 'estEST-202@mail.com', 'Jr. Los Olivos 162', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (264, 'Ana Lopez Mamani', '40000163', 'EST-203', 'estEST-203@mail.com', 'Jr. Los Olivos 163', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (265, 'Luis Gonzalez Huayta', '40000164', 'EST-204', 'estEST-204@mail.com', 'Jr. Los Olivos 164', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (266, 'Rosa Perez Ccama', '40000165', 'EST-205', 'estEST-205@mail.com', 'Jr. Los Olivos 165', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (267, 'Juan Sanchez Chambi', '40000166', 'EST-206', 'estEST-206@mail.com', 'Jr. Los Olivos 166', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (268, 'Carmen Ramirez Hancco', '40000167', 'EST-207', 'estEST-207@mail.com', 'Jr. Los Olivos 167', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (269, 'Pedro Torres Lipa', '40000168', 'EST-208', 'estEST-208@mail.com', 'Jr. Los Olivos 168', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (270, 'Elena Flores Turpo', '40000169', 'EST-209', 'estEST-209@mail.com', 'Jr. Los Olivos 169', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (271, 'Diego Rivera Coila', '40000170', 'EST-210', 'estEST-210@mail.com', 'Jr. Los Olivos 170', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (272, 'Sofia Castillo Yana', '40000171', 'EST-211', 'estEST-211@mail.com', 'Jr. Los Olivos 171', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (273, 'Miguel Reyes Apaza', '40000172', 'EST-212', 'estEST-212@mail.com', 'Jr. Los Olivos 172', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (274, 'Andrea Ortiz Sucasaire', '40000173', 'EST-213', 'estEST-213@mail.com', 'Jr. Los Olivos 173', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (275, 'Pablo Morales Huanca', '40000174', 'EST-214', 'estEST-214@mail.com', 'Jr. Los Olivos 174', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (276, 'Valeria Delgado Umiña', '40000175', 'EST-215', 'estEST-215@mail.com', 'Jr. Los Olivos 175', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (277, 'Fernando Cruz Chura', '40000176', 'EST-216', 'estEST-216@mail.com', 'Jr. Los Olivos 176', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (278, 'Camila Ramos Ticona', '40000177', 'EST-217', 'estEST-217@mail.com', 'Jr. Los Olivos 177', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (279, 'Sergio Vargas Pari', '40000178', 'EST-218', 'estEST-218@mail.com', 'Jr. Los Olivos 178', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (280, 'Lucia Mendoza Vilca', '40000179', 'EST-219', 'estEST-219@mail.com', 'Jr. Los Olivos 179', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (281, 'Carlos Garcia Huaman', '40000180', 'EST-220', 'estEST-220@mail.com', 'Jr. Los Olivos 180', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (282, 'Maria Rodriguez Quispe', '40000181', 'EST-221', 'estEST-221@mail.com', 'Jr. Los Olivos 181', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (283, 'Jose Martinez Condori', '40000182', 'EST-222', 'estEST-222@mail.com', 'Jr. Los Olivos 182', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (284, 'Ana Lopez Mamani', '40000183', 'EST-223', 'estEST-223@mail.com', 'Jr. Los Olivos 183', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (285, 'Luis Gonzalez Huayta', '40000184', 'EST-224', 'estEST-224@mail.com', 'Jr. Los Olivos 184', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (286, 'Rosa Perez Ccama', '40000185', 'EST-225', 'estEST-225@mail.com', 'Jr. Los Olivos 185', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (287, 'Juan Sanchez Chambi', '40000186', 'EST-226', 'estEST-226@mail.com', 'Jr. Los Olivos 186', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (288, 'Carmen Ramirez Hancco', '40000187', 'EST-227', 'estEST-227@mail.com', 'Jr. Los Olivos 187', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (289, 'Pedro Torres Lipa', '40000188', 'EST-228', 'estEST-228@mail.com', 'Jr. Los Olivos 188', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (290, 'Elena Flores Turpo', '40000189', 'EST-229', 'estEST-229@mail.com', 'Jr. Los Olivos 189', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (291, 'Diego Rivera Coila', '40000190', 'EST-230', 'estEST-230@mail.com', 'Jr. Los Olivos 190', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (292, 'Sofia Castillo Yana', '40000191', 'EST-231', 'estEST-231@mail.com', 'Jr. Los Olivos 191', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (293, 'Miguel Reyes Apaza', '40000192', 'EST-232', 'estEST-232@mail.com', 'Jr. Los Olivos 192', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (294, 'Andrea Ortiz Sucasaire', '40000193', 'EST-233', 'estEST-233@mail.com', 'Jr. Los Olivos 193', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (295, 'Pablo Morales Huanca', '40000194', 'EST-234', 'estEST-234@mail.com', 'Jr. Los Olivos 194', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (296, 'Valeria Delgado Umiña', '40000195', 'EST-235', 'estEST-235@mail.com', 'Jr. Los Olivos 195', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (297, 'Fernando Cruz Chura', '40000196', 'EST-236', 'estEST-236@mail.com', 'Jr. Los Olivos 196', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (298, 'Camila Ramos Ticona', '40000197', 'EST-237', 'estEST-237@mail.com', 'Jr. Los Olivos 197', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (299, 'Sergio Vargas Pari', '40000198', 'EST-238', 'estEST-238@mail.com', 'Jr. Los Olivos 198', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (300, 'Lucia Mendoza Vilca', '40000199', 'EST-239', 'estEST-239@mail.com', 'Jr. Los Olivos 199', '987654', 'Activo', NOW());
INSERT INTO iespp_db.estudiantes (id, nombre_completo, dni, codigo_estudiante, email, direccion, telefono, estado, fecha_registro) VALUES (301, 'Carlos Garcia Huaman', '40000200', 'EST-240', 'estEST-240@mail.com', 'Jr. Los Olivos 200', '987654', 'Activo', NOW());

INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (102, 2, NOW()), (102, 3, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (103, 4, NOW()), (103, 5, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (104, 7, NOW()), (104, 8, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (105, 9, NOW()), (105, 10, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (106, 11, NOW()), (106, 12, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (107, 13, NOW()), (107, 14, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (108, 15, NOW()), (108, 16, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (109, 17, NOW()), (109, 18, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (110, 19, NOW()), (110, 20, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (111, 21, NOW()), (111, 22, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (112, 23, NOW()), (112, 24, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (113, 25, NOW()), (113, 26, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (114, 27, NOW()), (114, 28, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (115, 29, NOW()), (115, 30, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (116, 31, NOW()), (116, 32, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (117, 33, NOW()), (117, 34, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (118, 35, NOW()), (118, 36, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (119, 37, NOW()), (119, 38, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (120, 39, NOW()), (120, 40, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (121, 41, NOW()), (121, 42, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (122, 43, NOW()), (122, 44, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (123, 45, NOW()), (123, 46, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (124, 47, NOW()), (124, 48, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (125, 49, NOW()), (125, 50, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (126, 51, NOW()), (126, 52, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (127, 53, NOW()), (127, 54, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (128, 55, NOW()), (128, 56, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (129, 57, NOW()), (129, 58, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (130, 59, NOW()), (130, 60, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (131, 61, NOW()), (131, 62, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (132, 63, NOW()), (132, 64, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (133, 65, NOW()), (133, 66, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (134, 68, NOW()), (134, 69, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (135, 70, NOW()), (135, 71, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (136, 72, NOW()), (136, 73, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (137, 74, NOW()), (137, 75, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (138, 76, NOW()), (138, 77, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (139, 78, NOW()), (139, 79, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (140, 80, NOW()), (140, 81, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (141, 82, NOW()), (141, 83, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (142, 84, NOW()), (142, 85, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (143, 86, NOW()), (143, 87, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (144, 88, NOW()), (144, 89, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (145, 90, NOW()), (145, 91, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (146, 92, NOW()), (146, 93, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (147, 94, NOW()), (147, 95, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (148, 96, NOW()), (148, 97, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (149, 98, NOW()), (149, 99, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (150, 100, NOW()), (150, 101, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (151, 102, NOW()), (151, 103, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (152, 104, NOW()), (152, 105, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (153, 106, NOW()), (153, 107, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (154, 108, NOW()), (154, 109, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (155, 110, NOW()), (155, 111, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (156, 112, NOW()), (156, 113, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (157, 114, NOW()), (157, 115, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (158, 116, NOW()), (158, 117, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (159, 118, NOW()), (159, 119, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (160, 120, NOW()), (160, 121, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (161, 122, NOW()), (161, 123, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (162, 124, NOW()), (162, 125, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (163, 126, NOW()), (163, 127, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (164, 128, NOW()), (164, 130, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (165, 131, NOW()), (165, 132, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (166, 133, NOW()), (166, 134, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (167, 135, NOW()), (167, 136, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (168, 137, NOW()), (168, 138, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (169, 139, NOW()), (169, 140, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (170, 141, NOW()), (170, 142, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (171, 143, NOW()), (171, 144, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (172, 145, NOW()), (172, 146, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (173, 147, NOW()), (173, 148, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (174, 149, NOW()), (174, 150, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (175, 151, NOW()), (175, 152, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (176, 153, NOW()), (176, 154, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (177, 155, NOW()), (177, 156, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (178, 157, NOW()), (178, 158, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (179, 159, NOW()), (179, 160, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (180, 161, NOW()), (180, 162, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (181, 163, NOW()), (181, 164, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (182, 165, NOW()), (182, 166, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (183, 167, NOW()), (183, 168, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (184, 169, NOW()), (184, 170, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (185, 171, NOW()), (185, 172, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (186, 173, NOW()), (186, 174, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (187, 175, NOW()), (187, 176, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (188, 177, NOW()), (188, 178, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (189, 179, NOW()), (189, 180, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (190, 181, NOW()), (190, 182, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (191, 183, NOW()), (191, 184, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (192, 185, NOW()), (192, 186, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (193, 188, NOW()), (193, 189, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (194, 190, NOW()), (194, 191, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (195, 193, NOW()), (195, 194, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (196, 195, NOW()), (196, 196, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (197, 197, NOW()), (197, 198, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (198, 199, NOW()), (198, 200, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (199, 201, NOW()), (199, 202, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (200, 203, NOW()), (200, 204, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (201, 205, NOW()), (201, 206, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (202, 207, NOW()), (202, 208, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (203, 209, NOW()), (203, 210, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (204, 211, NOW()), (204, 212, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (205, 213, NOW()), (205, 214, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (206, 215, NOW()), (206, 216, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (207, 217, NOW()), (207, 218, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (208, 219, NOW()), (208, 220, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (209, 221, NOW()), (209, 222, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (210, 223, NOW()), (210, 224, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (211, 225, NOW()), (211, 226, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (212, 227, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (213, 228, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (214, 229, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (215, 230, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (216, 231, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (217, 232, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (218, 233, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (219, 234, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (220, 235, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (221, 236, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (222, 237, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (223, 238, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (224, 239, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (225, 240, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (226, 241, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (227, 242, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (228, 243, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (229, 244, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (230, 245, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (231, 246, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (232, 247, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (233, 248, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (234, 249, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (235, 250, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (236, 251, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (237, 252, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (238, 253, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (239, 254, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (240, 255, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (241, 256, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (242, 257, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (243, 258, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (244, 259, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (245, 260, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (246, 261, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (247, 262, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (248, 263, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (249, 264, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (250, 265, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (251, 266, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (252, 267, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (253, 268, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (254, 269, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (255, 270, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (256, 271, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (257, 272, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (258, 273, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (259, 274, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (260, 275, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (261, 276, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (262, 277, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (263, 278, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (264, 279, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (265, 280, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (266, 281, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (267, 282, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (268, 283, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (269, 284, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (270, 285, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (271, 286, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (272, 287, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (273, 288, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (274, 289, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (275, 290, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (276, 291, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (277, 292, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (278, 293, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (279, 294, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (280, 295, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (281, 296, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (282, 297, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (283, 298, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (284, 299, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (285, 300, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (286, 301, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (287, 302, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (288, 303, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (289, 304, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (290, 305, NOW());
INSERT INTO iespp_db.matriculas (estudiante_id, curso_id, fecha_matricula) VALUES (291, 306, NOW());

ALTER TABLE iespp_db.estudiantes AUTO_INCREMENT = 302;
SET FOREIGN_KEY_CHECKS=1;
