# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://spring.informaticapp.com:3306/cevicherias_iespp_db?useSSL=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
spring.datasource.username=cevicherias_jordy
spring.datasource.password=Jhork@321

# Hibernate (Crea las tablas automáticamente según nuestros modelos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8080

# ===============================
# CONFIGURACIÓN DE SEGURIDAD JWT
# ===============================
# Esta es la llave secreta para firmar los tokens (debe ser larga y compleja)
jwt.secret=UnaClaveSuperSecretaParaElInstitutoPedagogicoMonseñorEliasOlazar2026
jwt.expiration=86400000

# ===============================
# OAUTH2 GOOGLE (Lo llenaremos después con las credenciales de Google Cloud)
# ===============================
spring.security.oauth2.client.registration.google.client-id=TU_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=TU_CLIENT_SECRET




# ===============================
# INICIALIZACIÓN DE DATOS
# ===============================
spring.jpa.defer-datasource-initialization=true

# ===============================
# CONFIGURACIÓN DE CORREO (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jordycurayacosta@gmail.com
# Coloca aquí la contraseña de 16 dígitos generada por Google, SIN ESPACIOS
spring.mail.password=uprnjthhnbdwxvth
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



